Repository 10kumaranurag01/todo-done-express, pull requests merged in 2024-10, with the labels that each got.

#3 Sourabh782- Implemented forgot password endpoints
  controllers/authController.js
  controllers/taskController.js
  middlewares/authMiddleware.js
  routes/authRoutes.js
Labels: hacktoberfest-accepted

#6 feat: add Docker & Docker Compose
  .dockerignore
  .env.example
  Dockerfile
  app.js
  compose.yaml
  package.json
Labels: enhancement, hacktoberfest-accepted

#8 feat: add ratelimit & refactored code.
  .env.example
  .gitignore
  app.js
  controllers/authController.js
  controllers/taskController.js
  middlewares/authMiddleware.js
  models/Task.js
  package-lock.json
  package.json
  ratelimitTest.js
  utils/asyncHandler.js
  utils/corsOptions.js
  utils/generateToken.js
  utils/isEmail.js
  utils/rateLimit.js
  utils/updateUserPassword.js
  utils/validateData.js
  validators/validate.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
